platform :ios, '9.0'

target 'DoubleLink' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'Alamofire'
  #pod 'ObjectMapper'
  pod 'YYModel'
  pod 'SDWebImage'
end
